In [1]:
import pandas as pd
file = pd.read_csv('wine_dataset.csv')

In [2]:
file.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [3]:
file['style'] = file['style'].replace('red', 0)

In [4]:
file['style'] = file['style'].replace('white', 1)

In [5]:
file

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [6]:
# Preditores e alvo
y = file['style']
x = file.drop('style', axis = 1)

In [7]:
x.shape

(6497, 12)

In [8]:
y.shape

(6497,)

In [9]:
from sklearn.model_selection import train_test_split

# Conjuntos de treino e teste
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [10]:
from sklearn.ensemble import ExtraTreesClassifier

# Modelo
model = ExtraTreesClassifier()
model.fit(x_train, y_train)

# Imprimindo resultado
result = model.score(x_test, y_test)
print('Precision:', result)

Precision: 0.9969230769230769

In [11]:
y_test[400:403]

3233    1
1827    1
6320    1
Name: style, dtype: int64

In [12]:
x_test[400:403]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
3233,8.3,0.25,0.49,16.8,0.048,50.0,228.0,1.00010,3.03,0.52,9.2,6
1827,6.4,0.17,0.32,2.4,0.048,41.0,200.0,0.99380,3.50,0.50,9.7,6
6320,6.1,0.32,0.33,10.7,0.036,27.0,98.0,0.99521,3.34,0.52,10.2,6

In [13]:
prediction = model.predict(x_test[400:403])

In [14]:
prediction

array([1, 1, 1])